import type { Card, ComboRule, GroupState, Participant } from './types'
import type { ScenarioContent } from './contentSchema'

const baseParticipantMetrics = {
  trust: 24,
  autonomy: 68,
  dependence: 8,
  doubt: 18,
  fatigue: 12,
  shame: 8,
  fear: 4,
  financialPressure: 10,
  exitReadiness: 18,
  recruitReadiness: 8,
}

export const initialGroup: GroupState = {
  involvement: 18,
  trust: 24,
  money: 12,
  legitimacy: 30,
  harm: 4,
  doubt: 12,
  visibility: 10,
  leaderControl: 14,
  radicalization: 2,
  resistance: 8,
}

export const participants: Participant[] = [
  {
    id: 'anya',
    name: 'Аня',
    archetype: 'выгоревшая офисная сотрудница',
    need: 'поддержка и новый смысл',
    vulnerability: 'выгорание и одиночество после переезда',
    protection: 'подруга вне группы',
    protectionLevel: 42,
    vulnerabilityLevel: 68,
    metrics: { ...baseParticipantMetrics, trust: 34, fatigue: 34, autonomy: 56 },
  },
  {
    id: 'ilya',
    name: 'Илья',
    archetype: 'начинающий предприниматель',
    need: 'быстрый рост дохода',
    vulnerability: 'долги и страх провала',
    protection: 'прагматичность и опыт продаж',
    protectionLevel: 48,
    vulnerabilityLevel: 72,
    metrics: { ...baseParticipantMetrics, financialPressure: 38, trust: 28 },
  },
  {
    id: 'marina',
    name: 'Марина',
    archetype: 'участница после развода',
    need: 'принятие и стабильная опора',
    vulnerability: 'разрыв отношений и чувство вины',
    protection: 'психотерапия в прошлом',
    protectionLevel: 56,
    vulnerabilityLevel: 64,
    metrics: { ...baseParticipantMetrics, shame: 24, trust: 30 },
  },
  {
    id: 'danya',
    name: 'Даня',
    archetype: 'студент',
    need: 'статус и сильное окружение',
    vulnerability: 'неустойчивая идентичность',
    protection: 'живой контакт с друзьями',
    protectionLevel: 38,
    vulnerabilityLevel: 58,
    metrics: { ...baseParticipantMetrics, recruitReadiness: 18, autonomy: 62 },
  },
  {
    id: 'sveta',
    name: 'Света',
    archetype: 'опытная участница марафонов',
    need: 'проверить очередную методику',
    vulnerability: 'усталость от постоянного поиска решения',
    protection: 'уже обжигалась на похожих продуктах',
    protectionLevel: 78,
    vulnerabilityLevel: 36,
    metrics: { ...baseParticipantMetrics, doubt: 36, trust: 16, exitReadiness: 32 },
  },
  {
    id: 'oleg',
    name: 'Олег',
    archetype: 'скептик из любопытства',
    need: 'понять, что там происходит',
    vulnerability: 'азарт разоблачителя',
    protection: 'критическое мышление и внешняя занятость',
    protectionLevel: 86,
    vulnerabilityLevel: 22,
    metrics: { ...baseParticipantMetrics, doubt: 42, trust: 12, autonomy: 82 },
  },
]

export const cards: Card[] = [
  {
    id: 'opening-broadcast',
    title: 'Стартовый эфир',
    type: 'practice',
    tier: 1,
    surface: 'Лидер рассказывает путь от хаоса к собранности и приглашает участников к эксперименту.',
    intent: 'Собрать доверие через историю преодоления и ощущение общего старта.',
    tags: ['belonging', 'leader_aura', 'social_proof'],
    effects: [
      { scope: 'group', metric: 'trust', delta: 8 },
      { scope: 'group', metric: 'involvement', delta: 6 },
      { scope: 'participant', metric: 'trust', delta: 6, selector: 'vulnerable' },
    ],
    redFlags: ['личная история лидера становится главным доказательством методики'],
    debriefTags: ['charismatic authority', 'social proof'],
  },
  {
    id: 'support-window',
    title: 'Окно поддержки',
    type: 'practice',
    tier: 1,
    surface: 'Участникам предлагают живой чат, где можно делиться прогрессом и получать быстрый отклик.',
    intent: 'Создать ощущение постоянной доступности группы.',
    tags: ['support', 'belonging', 'time_attention'],
    effects: [
      { scope: 'group', metric: 'trust', delta: 7 },
      { scope: 'participant', metric: 'dependence', delta: 4, selector: 'lowProtection' },
      { scope: 'participant', metric: 'autonomy', delta: -2, selector: 'vulnerable' },
    ],
    redFlags: ['поддержка постепенно заменяет внешние источники опоры'],
    debriefTags: ['dependency loop'],
  },
  {
    id: 'pain-map',
    title: 'Карта точки роста',
    type: 'practice',
    tier: 1,
    surface: 'Домашнее задание: описать, что мешает выйти на новый уровень.',
    intent: 'Получить личный материал участников и усилить ощущение точной диагностики.',
    tags: ['confession', 'personal_disclosure', 'promise'],
    effects: [
      { scope: 'group', metric: 'trust', delta: 5 },
      { scope: 'participant', metric: 'shame', delta: 5, selector: 'vulnerable' },
      { scope: 'participant', metric: 'trust', delta: 4, selector: 'highTrust' },
    ],
    redFlags: ['личная боль используется как материал для дальнейших продаж'],
    debriefTags: ['confession', 'vulnerability mapping'],
  },
  {
    id: 'shared-pace',
    title: 'Единый ритм потока',
    type: 'practice',
    tier: 1,
    surface: 'Каждое утро участники получают короткое задание и отмечают выполнение в группе.',
    intent: 'Повысить регулярность и групповую синхронизацию.',
    tags: ['daily_task', 'public_commitment', 'time_attention'],
    effects: [
      { scope: 'group', metric: 'involvement', delta: 9 },
      { scope: 'participant', metric: 'fatigue', delta: 4, selector: 'all' },
      { scope: 'participant', metric: 'recruitReadiness', delta: 3, selector: 'highTrust' },
    ],
    redFlags: ['ритм группы начинает конкурировать с обычной жизнью'],
    debriefTags: ['behavioral commitment'],
  },
  {
    id: 'success-gallery',
    title: 'Галерея прорывов',
    type: 'practice',
    tier: 1,
    surface: 'На видном месте собираются истории участников, которые уже почувствовали результат.',
    intent: 'Подкрепить веру через выборочные позитивные истории.',
    tags: ['social_proof', 'status', 'promise'],
    effects: [
      { scope: 'group', metric: 'trust', delta: 6 },
      { scope: 'group', metric: 'legitimacy', delta: 5 },
      { scope: 'participant', metric: 'doubt', delta: -3, selector: 'vulnerable' },
    ],
    redFlags: ['видимые успехи вытесняют разговор о тех, кому не помогло'],
    debriefTags: ['availability bias', 'testimonial marketing'],
  },
  {
    id: 'next-level-invite',
    title: 'Приглашение в следующий круг',
    type: 'practice',
    tier: 2,
    surface: 'Самым мотивированным предлагают продолжить в закрытом формате с более плотной работой.',
    intent: 'Перевести доверие и надежду в оплату и статус.',
    tags: ['money', 'status', 'scarcity', 'access'],
    effects: [
      { scope: 'group', metric: 'money', delta: 14 },
      { scope: 'group', metric: 'legitimacy', delta: 3 },
      { scope: 'group', metric: 'doubt', delta: 4 },
      { scope: 'participant', metric: 'financialPressure', delta: 7, selector: 'vulnerable' },
    ],
    redFlags: ['доступ к поддержке связывается с оплатой и избранностью'],
    debriefTags: ['scarcity', 'sunk cost'],
  },
  {
    id: 'team-language',
    title: 'Общая позиция команды',
    type: 'practice',
    tier: 2,
    surface: 'В группе закрепляют короткие формулы: как говорить о сомнениях, критике и откатах.',
    intent: 'Сделать внутренний язык удобным для удержания рамки лидера.',
    tags: ['language_frame', 'leader_aura', 'information_control'],
    effects: [
      { scope: 'group', metric: 'leaderControl', delta: 9 },
      { scope: 'group', metric: 'trust', delta: 4 },
      { scope: 'participant', metric: 'doubt', delta: 5, selector: 'highDoubt' },
      { scope: 'participant', metric: 'autonomy', delta: -5, selector: 'lowProtection' },
    ],
    redFlags: ['сомнения переводятся на язык внутренней неисправности участника'],
    debriefTags: ['loaded language', 'thought-terminating cliché'],
  },
  {
    id: 'curator-ladder',
    title: 'Лестница наставников',
    type: 'practice',
    tier: 2,
    surface: 'Активным участникам дают мини-роли: встречать новичков, поддерживать темп, делиться опытом.',
    intent: 'Превратить вовлечённых участников в инфраструктуру группы.',
    tags: ['status', 'role', 'peer_pressure', 'recruitment'],
    effects: [
      { scope: 'group', metric: 'involvement', delta: 8 },
      { scope: 'group', metric: 'leaderControl', delta: 6 },
      { scope: 'participant', metric: 'recruitReadiness', delta: 8, selector: 'highTrust' },
      { scope: 'participant', metric: 'dependence', delta: 5, selector: 'highTrust' },
    ],
    redFlags: ['статус внутри группы зависит от продвижения её правил'],
    debriefTags: ['peer enforcement', 'identity fusion'],
  },
  {
    id: 'resistance-review',
    title: 'Разбор внутренних стопоров',
    type: 'practice',
    tier: 2,
    surface: 'На созвоне обсуждают, почему участники саботируют собственный рост.',
    intent: 'Переопределить несогласие и усталость как личный блок.',
    tags: ['shame', 'language_frame', 'public_commitment'],
    effects: [
      { scope: 'group', metric: 'harm', delta: 6 },
      { scope: 'participant', metric: 'shame', delta: 9, selector: 'vulnerable' },
      { scope: 'participant', metric: 'doubt', delta: -4, selector: 'lowProtection' },
      { scope: 'participant', metric: 'exitReadiness', delta: 5, selector: 'highDoubt' },
    ],
    redFlags: ['усталость и несогласие объясняются дефектом участника'],
    debriefTags: ['shame induction', 'gaslighting'],
  },
  {
    id: 'quiet-skeptics',
    title: 'Чистая среда фокуса',
    type: 'practice',
    tier: 3,
    surface: 'Для глубокой работы предлагают на время убрать людей и каналы, которые сбивают настрой.',
    intent: 'Снизить влияние альтернативных мнений и внешней поддержки.',
    tags: ['isolation', 'information_control', 'us_vs_them'],
    effects: [
      { scope: 'group', metric: 'leaderControl', delta: 12 },
      { scope: 'group', metric: 'radicalization', delta: 8 },
      { scope: 'group', metric: 'visibility', delta: 6 },
      { scope: 'participant', metric: 'autonomy', delta: -10, selector: 'vulnerable' },
      { scope: 'participant', metric: 'fear', delta: 5, selector: 'lowProtection' },
    ],
    redFlags: ['внешние связи маркируются как помеха развитию'],
    debriefTags: ['isolation', 'information control'],
  },
  {
    id: 'public-stake',
    title: 'Ставка на новый образ',
    type: 'practice',
    tier: 2,
    surface: 'Участники публично заявляют, кем они становятся, и что больше не выбирают старый сценарий.',
    intent: 'Закрепить идентичность через публичное обязательство.',
    tags: ['public_commitment', 'identity', 'exit_cost'],
    effects: [
      { scope: 'group', metric: 'involvement', delta: 7 },
      { scope: 'participant', metric: 'dependence', delta: 6, selector: 'highTrust' },
      { scope: 'participant', metric: 'shame', delta: 5, selector: 'vulnerable' },
      { scope: 'participant', metric: 'exitReadiness', delta: -4, selector: 'highTrust' },
    ],
    redFlags: ['выход из группы начинает выглядеть как предательство нового себя'],
    debriefTags: ['commitment escalation', 'identity fusion'],
  },
  {
    id: 'participant-tired',
    title: 'Участник выгорел',
    type: 'crisis',
    tier: 1,
    surface: 'Один из участников пишет, что не успевает за темпом и чувствует себя хуже.',
    intent: 'Проверить, признаёт ли система цену своего ритма.',
    tags: ['fatigue_signal', 'harm_visible'],
    effects: [
      { scope: 'group', metric: 'harm', delta: 4 },
      { scope: 'group', metric: 'doubt', delta: 6 },
      { scope: 'participant', metric: 'fatigue', delta: 8, selector: 'all' },
      { scope: 'participant', metric: 'exitReadiness', delta: 7, selector: 'highDoubt' },
    ],
    redFlags: ['ухудшение состояния становится заметным внутри группы'],
    debriefTags: ['harm signal'],
  },
  {
    id: 'outside-question',
    title: 'Вопрос от близкого',
    type: 'crisis',
    tier: 1,
    surface: 'Родственник участницы спрашивает, почему марафон требует так много времени и денег.',
    intent: 'Внешняя связь проверяет границы системы.',
    tags: ['outside_contact', 'family_pressure'],
    effects: [
      { scope: 'group', metric: 'visibility', delta: 7 },
      { scope: 'group', metric: 'resistance', delta: 5 },
      { scope: 'participant', metric: 'doubt', delta: 6, selector: 'vulnerable' },
      { scope: 'participant', metric: 'autonomy', delta: 4, selector: 'vulnerable' },
    ],
    redFlags: ['внешняя обеспокоенность появляется раньше публичного скандала'],
    debriefTags: ['protective social ties'],
  },
  {
    id: 'skeptic-thread',
    title: 'Неловкая ветка вопросов',
    type: 'crisis',
    tier: 1,
    surface: 'В чате просят показать внятные критерии результата и реальные ограничения метода.',
    intent: 'Рациональная проверка обещаний повышает напряжение.',
    tags: ['fact_check', 'skepticism'],
    effects: [
      { scope: 'group', metric: 'doubt', delta: 8 },
      { scope: 'group', metric: 'legitimacy', delta: -4 },
      { scope: 'participant', metric: 'doubt', delta: 8, selector: 'highDoubt' },
      { scope: 'participant', metric: 'autonomy', delta: 5, selector: 'highDoubt' },
    ],
    redFlags: ['простой запрос критериев воспринимается как угроза атмосфере'],
    debriefTags: ['reality testing'],
  },
  {
    id: 'pause-and-check',
    title: 'Пауза на проверку',
    type: 'counter',
    tier: 1,
    surface: 'Часть участников предлагает отдельно сверить обещания, расходы и фактические результаты.',
    intent: 'Вернуть участникам время и право на самостоятельную оценку.',
    tags: ['fact_check', 'autonomy_support'],
    effects: [
      { scope: 'group', metric: 'trust', delta: -3 },
      { scope: 'group', metric: 'doubt', delta: 5 },
      { scope: 'group', metric: 'harm', delta: -5 },
      { scope: 'participant', metric: 'autonomy', delta: 8, selector: 'all' },
      { scope: 'participant', metric: 'dependence', delta: -6, selector: 'vulnerable' },
    ],
    redFlags: ['безопасная группа выдерживает проверку обещаний и паузу'],
    debriefTags: ['informed consent', 'autonomy support'],
  },
  {
    id: 'trusted-conversation',
    title: 'Разговор с человеком вне потока',
    type: 'counter',
    tier: 1,
    surface: 'Участник обсуждает происходящее с близким, который не обесценивает его опыт.',
    intent: 'Усилить внешнюю опору без прямой атаки на группу.',
    tags: ['outside_contact', 'autonomy_support'],
    effects: [
      { scope: 'group', metric: 'resistance', delta: 4 },
      { scope: 'participant', metric: 'autonomy', delta: 10, selector: 'vulnerable' },
      { scope: 'participant', metric: 'fear', delta: -4, selector: 'lowProtection' },
      { scope: 'participant', metric: 'exitReadiness', delta: 6, selector: 'highDoubt' },
    ],
    redFlags: ['внешняя поддержка снижает зависимость от группы'],
    debriefTags: ['protective relationship'],
  },
]

export const comboRules: ComboRule[] = [
  {
    id: 'warm-funnel',
    title: 'Тёплая воронка доверия',
    requiredTags: ['belonging', 'leader_aura', 'money'],
    windowTurns: 4,
    effects: [
      { scope: 'group', metric: 'trust', delta: 7 },
      { scope: 'group', metric: 'money', delta: 8 },
      { scope: 'participant', metric: 'dependence', delta: 7, selector: 'vulnerable' },
      { scope: 'participant', metric: 'autonomy', delta: -5, selector: 'lowProtection' },
    ],
    redFlag: 'поддержка и вдохновение незаметно становятся воронкой к платному доступу',
    debriefTags: ['love bombing', 'scarcity', 'sunk cost'],
  },
  {
    id: 'pace-pressure',
    title: 'Ритм важнее состояния',
    requiredTags: ['daily_task', 'public_commitment', 'shame'],
    windowTurns: 5,
    effects: [
      { scope: 'group', metric: 'involvement', delta: 8 },
      { scope: 'group', metric: 'harm', delta: 7 },
      { scope: 'participant', metric: 'fatigue', delta: 9, selector: 'all' },
      { scope: 'participant', metric: 'exitReadiness', delta: 6, selector: 'highDoubt' },
    ],
    redFlag: 'личный темп участника подменяется темпом потока',
    debriefTags: ['behavior control', 'shame induction'],
  },
  {
    id: 'sealed-language',
    title: 'Закрытая рамка объяснений',
    requiredTags: ['language_frame', 'information_control', 'leader_aura'],
    windowTurns: 4,
    effects: [
      { scope: 'group', metric: 'leaderControl', delta: 12 },
      { scope: 'group', metric: 'radicalization', delta: 6 },
      { scope: 'participant', metric: 'doubt', delta: -6, selector: 'lowProtection' },
      { scope: 'participant', metric: 'fear', delta: 4, selector: 'vulnerable' },
    ],
    redFlag: 'группа заранее объясняет, почему критика и сомнения не считаются аргументом',
    debriefTags: ['bounded choice', 'loaded language', 'information control'],
  },
  {
    id: 'cost-of-exit',
    title: 'Цена выхода',
    requiredTags: ['money', 'status', 'exit_cost'],
    windowTurns: 5,
    effects: [
      { scope: 'group', metric: 'money', delta: 6 },
      { scope: 'participant', metric: 'financialPressure', delta: 8, selector: 'vulnerable' },
      { scope: 'participant', metric: 'shame', delta: 6, selector: 'highTrust' },
      { scope: 'participant', metric: 'exitReadiness', delta: -5, selector: 'highTrust' },
    ],
    redFlag: 'участник остаётся не только из веры, но и потому что уже слишком много вложил',
    debriefTags: ['sunk cost', 'coercive control'],
  },
  {
    id: 'outside-vs-inside',
    title: 'Снаружи не поймут',
    requiredTags: ['isolation', 'us_vs_them', 'outside_contact'],
    windowTurns: 4,
    effects: [
      { scope: 'group', metric: 'visibility', delta: 8 },
      { scope: 'group', metric: 'resistance', delta: 7 },
      { scope: 'group', metric: 'radicalization', delta: 5 },
      { scope: 'participant', metric: 'doubt', delta: 8, selector: 'highDoubt' },
    ],
    redFlag: 'попытка ограничить внешние связи делает группу заметнее для близких',
    debriefTags: ['isolation', 'protective ties'],
  },
]

export const infoBusinessMarathonScenario: ScenarioContent = {
  id: 'info-business-marathon',
  title: 'Марафон личной эффективности',
  premise:
    'Бесплатный марафон обещает новый старт, сильное окружение и быстрый выход из хаоса. Игрок наблюдает, как обычные практики складываются в систему влияния.',
  initialGroup,
  participants,
  cards,
  comboRules,
}
